language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - "pip install -r src/requirements.txt --use-mirrors"
  - "pip install -r tests/requirements.txt --use-mirrors"

script:
  - "py.test tests/ -v --cov src/caper --cov-report term-missing"

after_success:
  - coveralls